"""empty message

Revision ID: 1f7659415ca8
Revises: 32030a4335e2
Create Date: 2018-05-20 22:23:49.380455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7659415ca8'
down_revision = '32030a4335e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['hash'])
    op.add_column('products', sa.Column('image_hash', sa.String(length=255), nullable=True))
    op.drop_constraint('products_image_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'images', ['image_hash'], ['hash'])
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_image_id_fkey', 'products', 'images', ['image_id'], ['id'])
    op.drop_column('products', 'image_hash')
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
