"""empty message

Revision ID: 32030a4335e2
Revises: d24623be3316
Create Date: 2018-05-20 22:12:14.822829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32030a4335e2'
down_revision = 'd24623be3316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_original')
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    op.add_column('images', sa.Column('is_original', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
