"""empty message

Revision ID: 33ef54b6b69a
Revises: d44f9ebca7cb
Create Date: 2018-05-22 13:00:57.349090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ef54b6b69a'
down_revision = 'd44f9ebca7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commentaries', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commentaries', 'answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commentaries', type_='foreignkey')
    op.drop_column('commentaries', 'answer_id')
    op.drop_table('answers')
    # ### end Alembic commands ###
