"""empty message

Revision ID: d44f9ebca7cb
Revises: df3f5a5ced48
Create Date: 2018-05-21 11:07:32.453465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44f9ebca7cb'
down_revision = 'df3f5a5ced48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('bought_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['bought_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'bought_by')
    # ### end Alembic commands ###
