"""empty message

Revision ID: df3f5a5ced48
Revises: 1f7659415ca8
Create Date: 2018-05-20 23:29:57.102476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3f5a5ced48'
down_revision = '1f7659415ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentaries', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commentaries', 'created_at')
    # ### end Alembic commands ###
